version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress-dev-password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - beaver
    labels:
      - traefik.enable=false

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    expose:
      - 80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
      - ./upload_max_size.ini:/usr/local/etc/php/conf.d/upload_max_size.ini
    labels:
      - traefik.enable=true
      - traefik.frontend.entryPoints="http,https"
      - traefik.http.routers.wordpress.rule=Host(`<DOMAIN_NAME>`)
      - traefik.http.routers.wordpress.tls=true
      - traefik.http.routers.wordpress.tls.certresolver=le
      - traefik.docker.network=web
    networks:
      - web
      - wordpress

networks:
  beaver:
    external: false
  web:
    external: true



